#!/bin/bash

FILE="$(date +'%s').html"
SCP="$(head -n 1 ~/.config/webcpy/config)"
WEB="$(tail -n 1 ~/.config/webcpy/config)"

if [ -p /dev/stdin ]; then
    # If piping
    echo "<html><head><meta charset=" > $FILE
    echo "utf-8" >> $FILE
    echo "><title>Raw paste data</title></head><body><pre>" >> $FILE
    while IFS= read line; do
        echo "${line}" | sed -r 's/&/\&amp;/g' | sed -r 's/</\&lt;/g' >> $FILE
    done
    echo "</pre></body></html>" >> $FILE
else
    if [ -f "$1" ]; then
        # If putting a file
        echo "<html><head><meta charset=" > $FILE
        echo "utf-8" >> $FILE
        echo "><title>$1</title></head><body><pre>" >> $FILE
        cat "$1" | sed -r 's/&/\&amp;/g' | sed -r 's/</\&lt;/g' >> $FILE
        echo "</pre></body></html>" >> $FILE
    else
        echo "No input given!"
    fi
fi

chmod 711 $FILE
# Putting the file to the server
scp $FILE $SCP

# Cleaning up
rm $FILE

# Copying the link
echo "$WEB$FILE" | xclip -selection clipboard