#!/bin/bash

FILE="$(date +'%s').html"
SCP="$(head -n 1 ~/.config/webcpy/config)"
WEB="$(tail -n 1 ~/.config/webcpy/config)"

if [ -p /dev/stdin ]; then
    # If piping
    echo "<html><head><meta charset=utf-8><title>Raw paste data</title></head><body><pre class=prettyprint style='border: none;'>" > $FILE
    while IFS= read line; do
        echo "${line}" | sed -r 's/&/\&amp;/g' | sed -r 's/</\&lt;/g' | sed -r 's/>/\&gt;/g' >> $FILE
    done
    echo "</pre></body><script src=https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js></script></html>" >> $FILE
else
    if [ -f "$1" ]; then
        # If putting a file
    echo "<html><head><meta charset=utf-8><title>$1</title></head><body><pre class=prettyprint style='border: none;'>" > $FILE
        cat "$1" | sed -r 's/&/\&amp;/g' | sed -r 's/</\&lt;/g' | sed -r 's/>/\&gt;/g' >> $FILE
        echo "</pre></body><script src=https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js></script></html>" >> $FILE
    else
        echo "No input given!"
    fi
fi

# Putting the file to the server
scp $FILE $SCP

# Cleaning up
rm $FILE

# Copying the link
echo "$WEB$FILE" | xclip -selection clipboard